CarmenMinikus/week_05/wednesday/library_app/config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#     authors GET    /authors(.:format)          authors#index
#             POST   /authors(.:format)          authors#create
#  new_author GET    /authors/new(.:format)      authors#new
# edit_author GET    /authors/:id/edit(.:format) authors#edit
#      author GET    /authors/:id(.:format)      authors#show
#             PATCH  /authors/:id(.:format)      authors#update
#             PUT    /authors/:id(.:format)      authors#update
#             DELETE /authors/:id(.:format)      authors#destroy

#       books GET    /books(.:format)            books#index
#             POST   /books(.:format)            books#create
#    new_book GET    /books/new(.:format)        books#new
#   edit_book GET    /books/:id/edit(.:format)   books#edit
#        book GET    /books/:id(.:format)        books#show
#             PATCH  /books/:id(.:format)        books#update
#             PUT    /books/:id(.:format)        books#update
#             DELETE /books/:id(.:format)        books#destroy
#


Rails.application.routes.draw do
  resources :authors, :books
end

CarmenMinikus/week_05/wednesday/library_app/app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id          :integer          not null, primary key
#  name        :text
#  dob         :text
#  nationality :text
#  image       :text
#

class Author < ActiveRecord::Base
  has_many :books
end

CarmenMinikus/week_05/wednesday/library_app/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id    :integer          not null, primary key
#  title :text
#  year  :text
#  genre :text
#  image :text
#

class Book < ActiveRecord::Base
  belongs_to :author
end

CarmenMinikus/week_05/wednesday/library_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

CarmenMinikus/week_05/wednesday/library_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find params[:id]
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.create author_params
    redirect_to author
  end

  def edit
    @author = Author.find params[:id]

  end

  def update
  end

  def destroy
    author = Author.find params[:id]
    author.destroy
    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:name, :dob, :nationality, :image)
  end
end

CarmenMinikus/week_05/wednesday/library_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create book_params
    redirect_to book
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    book = Book.find params[:id]
    book.update book_params
    redirect_to book
  end

  def show
    @book = Book.find params[:id]
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :year, :genre, :image, :author_id)
  end
end

CarmenMinikus/week_05/wednesday/library_app/app/helpers/application_helper.rb
module ApplicationHelper
end

CarmenMinikus/week_05/wednesday/library_app/app/helpers/author_helper.rb
module AuthorHelper
end

CarmenMinikus/week_05/wednesday/library_app/app/helpers/book_helper.rb
module BookHelper
end

CarmenMinikus/week_05/wednesday/library_app/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.label :dob %>
    <%= f.text_field :dob %>
  </fieldset>
  <fieldset>
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </fieldset>
  <fieldset>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </fieldset>
  <fieldset>
    <%= f.submit %>
  </fieldset>
<% end %>

CarmenMinikus/week_05/wednesday/library_app/app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %></h1>
<p>Find me in app/views/author/edit.html.erb</p>

CarmenMinikus/week_05/wednesday/library_app/app/views/authors/index.html.erb
<h1>All Authors</h1>
<% @authors.each do |author| %>
<%= image_tag(author.image, :class => "thumb") %>
  <ul>
    <li><%=link_to(author.name, author)%></li>
    <li><%= author.nationality %></li>
    <li><%= author.dob %></li>
  </ul>
<%end%>

CarmenMinikus/week_05/wednesday/library_app/app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render :partial => 'form' %>

CarmenMinikus/week_05/wednesday/library_app/app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<ul>
  <li>Born in: <%= @author.dob %></li>
  <li>nationality: <%= @author.nationality %></li>
</ul>
<%= image_tag(@author.image, :class => 'feature') %>
<div class="edit">
<%= link_to 'Edit Author', edit_author_path%>
<%= link_to 'Delete Author', @author, :method => :delete %>
</div>

CarmenMinikus/week_05/wednesday/library_app/app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>
  <fieldset>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </fieldset>
  <fieldset>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </fieldset>
  <fieldset>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </fieldset>
  <fieldset>
  <%= f.label :author_id %>
  <%= f.select :author_id, Author.pluck(:name, :id), :include_blank => true %>
</fieldset>
  <fieldset>
    <%= f.submit %>
  </fieldset>
<% end %>

CarmenMinikus/week_05/wednesday/library_app/app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render :partial => 'form' %>

CarmenMinikus/week_05/wednesday/library_app/app/views/books/index.html.erb
<h1>All Books</h1>
<% @books.each do |book| %>
<% if book.image.present? %>
  <%= image_tag(book.image, :class => "thumb") %>
<%end%>
  <ul>
    <li><%=link_to(book.title, book)%></li>
    <li><%= book.genre %></li>
    <li><%= book.year %></li>
  </ul>
<%end%>

CarmenMinikus/week_05/wednesday/library_app/app/views/books/new.html.erb
<h1>Add a Book</h1>
<%= render :partial => 'form' %>

CarmenMinikus/week_05/wednesday/library_app/app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<ul>
  <% unless @book.author.nil? %>

  <li>by: <%= link_to @book.author.name, @book.author %></li>
  <% end %>
<!--
  <% if @book.author != nil %>

<% end %>
 -->

  <li><%= @book.title %></li>
  <li>Year published: <%= @book.year %></li>
  <li>Genre: <%= @book.genre %></li>
</ul>
<div class="edit">
  <%= image_tag(@book.image, :class => 'feature') %>
  <%= link_to 'Edit Book', edit_book_path(@book) %>
  <%= link_to 'Delete Book', @book, :method => :delete %>
</div>

CarmenMinikus/week_05/wednesday/library_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <nav>
    <%= link_to 'All Authors', authors_path %>
    <%= link_to 'New Author', new_author_path %>
    <%= link_to 'All Books', books_path %>
    <%= link_to 'New Book', new_book_path %>
  </nav>
  <%= yield %>
</div>

</body>
</html>